#!/bin/sh
# 2016 Bibhas Acharya <mail@bibhas.com>
"exec" "python" "$0" "$@"

import os, sys
from implutils import *

if __name__ == "__main__":
  
    cd(PRJ_PRODUCT_DIR)

    os.system("sudo cp -r CMIOPluginTracer.plugin /Library/CoreMediaIO/Plug-Ins/DAL/")

    os.system("sudo cp -r CMIOPluginTracer.plugin /Library/CoreMediaIO/Plug-Ins/FCP-DAL/")

    color_log("Done!", "GREEN")
