#!/bin/sh
# 2016 Bibhas Acharya <mail@bibhas.com>
"exec" "python" "$0" "$@"

import os, sys
from implutils import *

if __name__ == "__main__":

  guessed_path = os.path.join(PRJ_PRODUCT_DIR, "tracer")

  if not os.path.exists(guessed_path):
    
    print "Could not find %s!!" % guessed_path

    exit(-1)

  os.system(guessed_path)
